"""Tests for SqlGenerator utility."""

from dq_autofix.preview import SqlGenerator


class TestQuoteIdentifier:
    """Tests for SqlGenerator.quote_identifier()."""

    def test_quotes_simple_name(self) -> None:
        """Test quoting simple identifier."""
        assert SqlGenerator.quote_identifier("column") == '"column"'

    def test_quotes_name_with_spaces(self) -> None:
        """Test quoting identifier with spaces."""
        assert SqlGenerator.quote_identifier("my column") == '"my column"'


class TestBuildUpdateSql:
    """Tests for SqlGenerator.build_update_sql()."""

    def test_build_update_sql(self) -> None:
        """Test UPDATE SQL generation."""
        sql = SqlGenerator.build_update_sql(
            table="schema.table",
            column="value",
            value_expr="100",
            where_clause='"value" IS NULL',
        )

        assert "UPDATE schema.table" in sql
        assert 'SET "value" = 100' in sql
        assert 'WHERE "value" IS NULL' in sql
        assert sql.endswith(";")

    def test_build_update_with_expression(self) -> None:
        """Test UPDATE with SQL expression."""
        sql = SqlGenerator.build_update_sql(
            table="schema.table",
            column="email",
            value_expr='TRIM("email")',
            where_clause='"email" != TRIM("email")',
        )

        assert 'TRIM("email")' in sql


class TestBuildDeleteSql:
    """Tests for SqlGenerator.build_delete_sql()."""

    def test_build_delete_sql(self) -> None:
        """Test DELETE SQL generation."""
        sql = SqlGenerator.build_delete_sql(
            table="schema.table",
            where_clause='"id" NOT IN (SELECT MIN("id") FROM schema.table GROUP BY "value")',
        )

        assert "DELETE FROM schema.table" in sql
        assert "WHERE" in sql
        assert sql.endswith(";")


class TestWrapInTransaction:
    """Tests for SqlGenerator.wrap_in_transaction()."""

    def test_wrap_in_transaction(self) -> None:
        """Test transaction wrapping."""
        sql = "UPDATE table SET col = 1;"
        wrapped = SqlGenerator.wrap_in_transaction(sql)

        assert wrapped.startswith("BEGIN;")
        assert "COMMIT;" in wrapped
        assert sql in wrapped

    def test_preserves_original_sql(self) -> None:
        """Test that original SQL is preserved."""
        sql = "UPDATE table SET col = 1;\nDELETE FROM other;"
        wrapped = SqlGenerator.wrap_in_transaction(sql)

        assert sql in wrapped


class TestAddDryRunComment:
    """Tests for SqlGenerator.add_dry_run_comment()."""

    def test_add_dry_run_comment(self) -> None:
        """Test dry-run comment addition."""
        sql = "UPDATE table SET col = 1;"
        result = SqlGenerator.add_dry_run_comment(sql)

        assert "DRY RUN" in result
        assert "Generated by DQ AutoFix" in result
        assert sql in result


class TestFormatSqlValue:
    """Tests for SqlGenerator.format_sql_value()."""

    def test_format_none(self) -> None:
        """Test formatting None."""
        assert SqlGenerator.format_sql_value(None) == "NULL"

    def test_format_string(self) -> None:
        """Test formatting string."""
        assert SqlGenerator.format_sql_value("hello") == "'hello'"

    def test_format_string_with_quotes(self) -> None:
        """Test formatting string with quotes."""
        assert SqlGenerator.format_sql_value("it's") == "'it''s'"

    def test_format_bool_true(self) -> None:
        """Test formatting True."""
        assert SqlGenerator.format_sql_value(True) == "TRUE"

    def test_format_bool_false(self) -> None:
        """Test formatting False."""
        assert SqlGenerator.format_sql_value(False) == "FALSE"

    def test_format_integer(self) -> None:
        """Test formatting integer."""
        assert SqlGenerator.format_sql_value(42) == "42"

    def test_format_float(self) -> None:
        """Test formatting float."""
        assert SqlGenerator.format_sql_value(3.14) == "3.14"


class TestGetTableParts:
    """Tests for SqlGenerator.get_table_parts()."""

    def test_full_fqn(self) -> None:
        """Test extracting parts from full FQN."""
        full_ref, simple_name = SqlGenerator.get_table_parts("db.schema.table")

        assert full_ref == "schema.table"
        assert simple_name == "table"

    def test_two_part_name(self) -> None:
        """Test extracting parts from two-part name."""
        full_ref, simple_name = SqlGenerator.get_table_parts("schema.table")

        assert full_ref == "schema.table"
        assert simple_name == "table"

    def test_simple_name(self) -> None:
        """Test extracting parts from simple name."""
        full_ref, simple_name = SqlGenerator.get_table_parts("table")

        assert full_ref == "table"
        assert simple_name == "table"
