"""Utilities for building SQL statements."""

from typing import Any


class SqlGenerator:
    """Utilities for building SQL statements."""

    @staticmethod
    def quote_identifier(name: str) -> str:
        """Quote an identifier for SQL.

        Args:
            name: Identifier name (column, table).

        Returns:
            Quoted identifier.
        """
        return f'"{name}"'

    @staticmethod
    def build_update_sql(
        table: str,
        column: str,
        value_expr: str,
        where_clause: str,
    ) -> str:
        """Build UPDATE statement.

        Args:
            table: Full table reference (schema.table).
            column: Column to update.
            value_expr: Value expression (literal or SQL expression).
            where_clause: WHERE condition.

        Returns:
            UPDATE SQL statement.
        """
        quoted_col = SqlGenerator.quote_identifier(column)
        return f"""UPDATE {table}
SET {quoted_col} = {value_expr}
WHERE {where_clause};"""

    @staticmethod
    def build_delete_sql(
        table: str,
        where_clause: str,
    ) -> str:
        """Build DELETE statement.

        Args:
            table: Full table reference (schema.table).
            where_clause: WHERE condition.

        Returns:
            DELETE SQL statement.
        """
        return f"""DELETE FROM {table}
WHERE {where_clause};"""

    @staticmethod
    def wrap_in_transaction(sql: str) -> str:
        """Wrap SQL in BEGIN/COMMIT transaction.

        Args:
            sql: SQL statement(s) to wrap.

        Returns:
            SQL wrapped in transaction.
        """
        return f"""BEGIN;

{sql}

COMMIT;"""

    @staticmethod
    def add_dry_run_comment(sql: str) -> str:
        """Add dry-run header comment.

        Args:
            sql: SQL statement(s).

        Returns:
            SQL with dry-run comment header.
        """
        return f"""-- DRY RUN: Review carefully before executing
-- Generated by DQ AutoFix

{sql}"""

    @staticmethod
    def format_sql_value(value: Any) -> str:
        """Format a Python value for SQL.

        Args:
            value: Python value to format.

        Returns:
            SQL-safe string representation.
        """
        if value is None:
            return "NULL"
        if isinstance(value, str):
            escaped = value.replace("'", "''")
            return f"'{escaped}'"
        if isinstance(value, bool):
            return "TRUE" if value else "FALSE"
        return str(value)

    @staticmethod
    def get_table_parts(fqn: str) -> tuple[str, str]:
        """Extract schema and table name from FQN.

        Args:
            fqn: Fully qualified name (e.g., 'db.schema.table').

        Returns:
            Tuple of (full_table_ref, simple_table_name).
        """
        parts = fqn.split(".")
        full_ref = f"{parts[-2]}.{parts[-1]}" if len(parts) >= 2 else parts[-1] if parts else fqn
        simple_name = parts[-1] if parts else fqn
        return full_ref, simple_name
